version: '3.8'

services:
  db:
    container_name: postgres_real_time_chat
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_time_chat
    ports:
      - "5433:5432"
    volumes:
      - postgres_real_time_chat_data:/var/lib/postgresql/data
    networks:
      - real_time_chat_network

volumes:
  postgres_real_time_chat_data:

networks:
  real_time_chat_network:
    driver: bridge
